-- MySQL Script generated by MySQL Workbench
-- Wed May  6 20:28:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Caterer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Caterer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Caterer` (
  `ShopID` INT NOT NULL,
  `PID` INT NOT NULL,
  `SID` INT NOT NULL,
  `ShopName` VARCHAR(45) NULL,
  `Menu` VARCHAR(100) NULL,
  `BillNumber` INT NOT NULL AUTO_INCREMENT,
  `Amount` FLOAT NULL,
  PRIMARY KEY (`ShopID`),
  CONSTRAINT `fk_PID`
    FOREIGN KEY (`PID`)
    REFERENCES `mydb`.`Passenger` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SID`
    FOREIGN KEY (`SID`)
    REFERENCES `mydb`.`Station` (`SID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_SID_idx` ON `mydb`.`Caterer` (`SID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_PID_idx` ON `mydb`.`Caterer` (`PID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EID` INT NOT NULL AUTO_INCREMENT,
  `TrainID` INT NOT NULL,
  `EFirstName` VARCHAR(50) NULL,
  `ELastName` VARCHAR(50) NULL,
  `EDepartment` VARCHAR(45) NULL,
  `EGender` VARCHAR(10) NULL,
  `EAge` INT NULL,
  `EDutyDays` VARCHAR(45) NULL,
  `EBaseSalary` INT NULL,
  `EIncentives` INT NULL,
  `EShift` VARCHAR(45) NULL,
  `ENetSalary` FLOAT GENERATED ALWAYS AS () VIRTUAL,
  `EYearsOfService` INT NULL,
  `EEmailID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EID`),
  CONSTRAINT `fk_TrainID`
    FOREIGN KEY (`TrainID`)
    REFERENCES `mydb`.`Train` (`TrainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TrainID_idx` ON `mydb`.`Employee` (`TrainID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Passenger` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `PFirstName` VARCHAR(45) NULL,
  `PLastName` VARCHAR(45) NULL,
  `PEmailID` VARCHAR(45) NULL,
  `PMobileNumber` VARCHAR(10) NULL,
  `PAge` INT NULL,
  `PGender` VARCHAR(10) NULL,
  PRIMARY KEY (`PID`))
ENGINE = InnoDB
COMMENT = '	';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Station` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Station` (
  `SID` INT NOT NULL,
  `SName` VARCHAR(45) NULL,
  `SEmployeesNumber` INT NULL,
  `SPlatformsNumber` INT NULL,
  `SWaitingRoomsNumber` INT NULL,
  `SFoodStallsNumber` INT NULL,
  `SInternetAvailability` VARCHAR(5) NULL,
  PRIMARY KEY (`SID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ticket` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `PNRNumber` INT NOT NULL,
  `TrainID` INT NOT NULL,
  `PID` INT NOT NULL,
  `DateOfJourney` VARCHAR(45) NULL,
  `BoardingStation` VARCHAR(45) NULL,
  `DestinationStation` VARCHAR(45) NULL,
  `TBasePrice` INT NULL,
  `TTax` INT NULL,
  `TicketCost` FLOAT GENERATED ALWAYS AS () VIRTUAL,
  `TBookingStatus` VARCHAR(20) NULL,
  `CoachClass` VARCHAR(10) NULL,
  PRIMARY KEY (`PNRNumber`),
  CONSTRAINT `fk_TrainID`
    FOREIGN KEY (`TrainID`)
    REFERENCES `mydb`.`Train` (`TrainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PID`
    FOREIGN KEY (`PID`)
    REFERENCES `mydb`.`Passenger` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TrainID_idx` ON `mydb`.`Ticket` (`TrainID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_PID_idx` ON `mydb`.`Ticket` (`PID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Train` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Train` (
  `TrainID` INT NOT NULL,
  `TrainName` VARCHAR(60) NULL,
  `ActiveDays` VARCHAR(70) NULL,
  `EID` INT NULL,
  `OriginStation` VARCHAR(45) NULL,
  `DestinationStation` VARCHAR(45) NULL,
  `JourneyTime` VARCHAR(30) NULL,
  `Passenger_PID` INT NOT NULL,
  PRIMARY KEY (`TrainID`),
  CONSTRAINT `fk_PID`
    FOREIGN KEY (`Passenger_PID`)
    REFERENCES `mydb`.`Passenger` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PID_idx` ON `mydb`.`Train` (`Passenger_PID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Train_has_Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Train_has_Station` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Train_has_Station` (
  `Train_Train Number` INT NOT NULL,
  `Station_Station ID` INT NOT NULL,
  PRIMARY KEY (`Train_Train Number`, `Station_Station ID`),
  CONSTRAINT `fk_Train_has_Station_Train1`
    FOREIGN KEY (`Train_Train Number`)
    REFERENCES `mydb`.`Train` (`TrainID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Train_has_Station_Station1`
    FOREIGN KEY (`Station_Station ID`)
    REFERENCES `mydb`.`Station` (`SID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Train_has_Station_Station1_idx` ON `mydb`.`Train_has_Station` (`Station_Station ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Train_has_Station_Train1_idx` ON `mydb`.`Train_has_Station` (`Train_Train Number` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
